### ISSUE TITLE
[pwa][ux] Improve avatars set

### ISSUE THREAD

**Issue by mk-emeks** [emeks-studio/sensum#59]
Some of the avatars are a little bit broken, and some of them were not included (from the original sheet) given there won't display properly.

![Screenshot(305)](https://github.com/emeks-studio/sensum/assets/7025445/dd675b1b-268d-4452-98cc-a3cb1c36a3ef)

[Avatars at: Frases.xlsx](https://github.com/emeks-studio/sensum/files/13328193/Frases.xlsx)

maybe by using different font form them we can fix this!
Ref. https://tailwindcss.com/docs/font-family

**Comment by santiagomonsech** [comment]
It seems that is not a problem of the font family itself, but of it's size and the margin that is defined in the box that contains them
![Screenshot from 2024-02-01 15-51-06](https://github.com/emeks-studio/sensum/assets/11459385/53cd9fa7-9309-49e5-9e5c-48fb53787c65)
