### ISSUE TITLE
[chore] Update Landing page

### ISSUE THREAD

**Issue by mk-emeks** [emeks-studio/sensum#66]
![Screenshot(309)](https://github.com/emeks-studio/sensum/assets/7025445/6ecbf0bc-604a-4424-8d95-b40285c25191)

^ once we have a version release at IPFS

- ref to sensum codebase
- ref to the telegram bot (shared-link)
- ref to sensumMessenger twitter account

Obs: Ideally the dapp should not have links targeting to external sources. That way we keep the code consistent in time. In the other hand, having a landing that targets to our release version is nice an decoupled.

**Comment by mirko-plowtech** [comment]
link: https://emeks.gitlab.io/sensum/

**Comment by bluesd** [comment]
Changes made.
If something needs to be refined, we should address it in a new specific issue.
